name: Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1 # Ruby
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - uses: actions/setup-node@v3 # Tailwind
        with:
          node-version: '18'

      - run: bundle install
      - run: npm install

      - run: npx tailwindcss -i ./assets/css/style.css -o ./assets/css/main.css --minify # Compile Tailwind
      - run: bundle exec jekyll build --baseurl "/portfolio" # Build Jekyll

      - uses: peaceiris/actions-gh-pages@v3 # Deploy to GitHub Pages
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./_site
          publish_branch: gh-pages
